"""rename address

Revision ID: 42374b4de7c1
Revises: beccd8ff3e3f
Create Date: 2023-11-13 16:35:24.225231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42374b4de7c1'
down_revision = 'beccd8ff3e3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('departments', sa.Column('location', sa.String(), nullable=True))
    # op.drop_column('departments', 'address')
    # ### end Alembic commands ###
    op.alter_column('departments', 'address', new_column_name='location')

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('departments', sa.Column('address', sa.VARCHAR(), nullable=True))
    # op.drop_column('departments', 'location')
    # ### end Alembic commands ###
    op.alter_column('departments', 'location', new_column_name='address')
